{{/*
────────────────────────────────────────────────────────────────────────────────
Hetzner RKE2 Cluster Template — Helpers
────────────────────────────────────────────────────────────────────────────────
*/}}

{{/*
Chart name (truncated to 63 chars for K8s label compliance).
*/}}
{{- define "hetzner-cluster-template.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Full cluster name — used as the primary resource name.
*/}}
{{- define "hetzner-cluster-template.clusterName" -}}
{{- required "cluster.name is required" .Values.cluster.name }}
{{- end }}

{{/*
Common labels applied to all resources.
*/}}
{{- define "hetzner-cluster-template.labels" -}}
helm.sh/chart: {{ include "hetzner-cluster-template.name" . }}-{{ .Chart.Version | replace "+" "_" }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/part-of: rancher-hetzner-cluster-templates
{{- end }}

{{/*
────────────────────────────────────────────────────────────────────────────────
CIS profile: host-level prerequisites (cloud-init userData)

DECISION: Auto-generate cloud-init to prepare hosts for RKE2 CIS profile.
Why: RKE2 CIS profile (profile: cis) checks host prerequisites at startup and
     exits with a fatal error if they're missing. The Hetzner Node Driver creates
     fresh Ubuntu VMs without these prerequisites. Cloud-init userData runs at
     first boot — before Rancher installs system-agent and RKE2 — so the host is
     ready by the time RKE2 starts.

Prerequisites (from https://docs.rke2.io/security/hardening_guide):
  1. etcd user/group must exist (CIS 1.1.12: etcd data dir owned by etcd:etcd)
  2. Kernel sysctl params must match kubelet protect-kernel-defaults expectations
────────────────────────────────────────────────────────────────────────────────
*/}}
{{- define "hetzner-cluster-template.cisUserData" -}}
#!/bin/bash
# RKE2 CIS profile: host-level prerequisites
# Auto-generated by hetzner-rke2-cluster-template when cisProfile.enabled=true
# See: https://docs.rke2.io/security/hardening_guide

# 1. Create etcd user and group (required by CIS 1.1.12)
# RKE2 refuses to start with CIS profile if etcd user doesn't exist.
useradd -r -c "etcd user" -s /sbin/nologin -M etcd -U 2>/dev/null || true

# 2. Set kernel parameters (required by protect-kernel-defaults=true)
# CIS profile enables protect-kernel-defaults on kubelet, which verifies
# these sysctl values match kubelet defaults. If they don't, RKE2 exits.
cat > /etc/sysctl.d/60-rke2-cis.conf << 'SYSCTL'
vm.panic_on_oom=0
vm.overcommit_memory=1
kernel.panic=10
kernel.panic_on_oops=1
SYSCTL
sysctl -p /etc/sysctl.d/60-rke2-cis.conf
{{- end }}
