{{/*
────────────────────────────────────────────────────────────────────────────────
Hetzner RKE2 Cluster Template — Helpers
────────────────────────────────────────────────────────────────────────────────
*/}}

{{/*
Chart name (truncated to 63 chars for K8s label compliance).
*/}}
{{- define "hetzner-cluster-template.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Full cluster name — used as the primary resource name.
*/}}
{{- define "hetzner-cluster-template.clusterName" -}}
{{- required "cluster.name is required" .Values.cluster.name }}
{{- end }}

{{/*
Common labels applied to all resources.
*/}}
{{- define "hetzner-cluster-template.labels" -}}
helm.sh/chart: {{ include "hetzner-cluster-template.name" . }}-{{ .Chart.Version | replace "+" "_" }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/part-of: rancher-hetzner-cluster-templates
{{- end }}

{{/*
────────────────────────────────────────────────────────────────────────────────
CIS profile: host-level prerequisites (Golden Image reference)

DECISION: CIS host prerequisites are delivered via Golden Image (Hetzner snapshot),
NOT via cloud-init userData. This helper is kept as a REFERENCE for what the Golden
Image must contain — it is not currently injected into HetznerConfig.

Why not userData: rancher-machine intercepts --hetzner-user-data (nameIsUserData()
matches any flag containing "user-data") and replaces the value with Rancher's
bootstrap cloud-init temp file. Inline CIS content is silently lost.

Prerequisites (from https://docs.rke2.io/security/hardening_guide):
  1. etcd user/group must exist (CIS 1.1.12: etcd data dir owned by etcd:etcd)
  2. Kernel sysctl params must match kubelet protect-kernel-defaults expectations
────────────────────────────────────────────────────────────────────────────────
*/}}
{{- define "hetzner-cluster-template.cisUserData" -}}
#!/bin/bash
# RKE2 CIS profile: host-level prerequisites
# Auto-generated by hetzner-rke2-cluster-template when cisProfile.enabled=true
# See: https://docs.rke2.io/security/hardening_guide

# 1. Create etcd user and group (required by CIS 1.1.12)
# RKE2 refuses to start with CIS profile if etcd user doesn't exist.
useradd -r -c "etcd user" -s /sbin/nologin -M etcd -U 2>/dev/null || true

# 2. Set kernel parameters (required by protect-kernel-defaults=true)
# CIS profile enables protect-kernel-defaults on kubelet, which verifies
# these sysctl values match kubelet defaults. If they don't, RKE2 exits.
cat > /etc/sysctl.d/60-rke2-cis.conf << 'SYSCTL'
vm.panic_on_oom=0
vm.overcommit_memory=1
kernel.panic=10
kernel.panic_on_oops=1
SYSCTL
sysctl -p /etc/sysctl.d/60-rke2-cis.conf
{{- end }}
