name: "Lint: helm"

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: helm lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      - run: helm lint ./charts

  template:
    name: helm template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      - run: |
          helm template test ./charts \
            --namespace fleet-default \
            --set cluster.name=test \
            --set cloudCredentialSecretName=test \
            --set hcloud.token=ci-dummy-token
