name: "SAST: KICS"

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  kics:
    name: KICS scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Run KICS
        uses: Checkmarx/kics-github-action@v2.1.20
        with:
          path: charts
          type: Helm
          fail_on: high
          output_formats: json
